name: '${project.name}'
version: '${project.version}'
main: lmaxplay.lifesteal.LifeSteal
api-version: 1.18
authors: ["Lmaxplay"]
depend: [ProtocolLib]
softdepend: [ProtocolLib]

commands:
  lifesteal:
    description: "Gives info about the SimpleLifeSteal plugin"
    #usage: "/lifesteal"
    permission: lifesteal.about

permissions:
  about:
    description: allow /lifesteal about
    default: true